version: "3"

services:
  cloudflared:
    container_name: cloudflared

    image: cloudflare/cloudflared:latest

    restart: unless-stopped

    networks:
      - cf-tunnel

    command:
      - tunnel
      - --no-autoupdate
      - run

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}

    labels:
      traefik.enable: false

networks:
  cf-tunnel:
    name: cf-tunnel
