version: "3"

services:
  nginx:
    container_name: nginx

    image: nginx

    networks:
      - cf-tunnel

    environment:
      - NGINX_HOST=${NGINX_HOST}

    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`test.$DOMAIN`)
      traefik.http.routers.nginx.entrypoints: web

networks:
  cf-tunnel:
    external: true
