version: "3"

services:
  vaultwarden:
    container_name: vaultwarden

    image: vaultwarden/server:latest

    restart: unless-stopped

    networks:
      - proxy

    volumes:
      - ./data:/data

    environment:
      DOMAIN: https://${VAULTWARDEN_DOMAIN}

    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`$VAULTWARDEN_DOMAIN`)
      traefik.http.routers.vaultwarden.entrypoints: web
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80

networks:
  proxy:
    external: true
