version: "3"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/prowlarr-config:/config
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: redirect-https@file
      traefik.http.routers.prowlarr.rule: Host(`$PROWLARR_DOMAIN`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/radarr-config:/config
      - ${MEDIA_ROOT}:/data
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.middlewares: redirect-https@file
      traefik.http.routers.radarr.rule: Host(`$RADARR_DOMAIN`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: true
      traefik.http.services.radarr.loadbalancer.server.port: 7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/sonarr-config:/config
      - ${MEDIA_ROOT}:/data
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.middlewares: redirect-https@file
      traefik.http.routers.sonarr.rule: Host(`$SONARR_DOMAIN`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: true
      traefik.http.services.sonarr.loadbalancer.server.port: 8989

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/sabnzbd-config:/config
      - ${MEDIA_ROOT}/usenet:/data/usenet
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.middlewares: redirect-https@file
      traefik.http.routers.sabnzbd.rule: Host(`$SABNZBD_DOMAIN`)
      traefik.http.routers.sabnzbd.entrypoints: websecure
      traefik.http.routers.sabnzbd.tls: true
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - ./data/qbittorrent-config:/config
      - ${MEDIA_ROOT}/torrents:/data/torrents
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.middlewares: redirect-https@file
      traefik.http.routers.qbittorrent.rule: Host(`$QBITTORRENT_DOMAIN`)
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.tls: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8081

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/overseerr-config:/config
    networks:
      - default
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`$OVERSEERR_DOMAIN`)
      traefik.http.routers.nginx.entrypoints: websecure
      traefik.http.services.nginx.loadbalancer.server.port: 5055

networks:
  proxy:
    external: true
