---
version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - cf-tunnel
    env_file:
      - .env
    labels:
      com.centurylinklabs.watchtower.enable: true
networks:
  cf-tunnel:
    external: true
