version: "3"

services:
  nginx:
    container_name: nginx

    image: nginx

    networks:
      - proxy

    environment:
      - NGINX_HOST=${NGINX_DOMAIN}

    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`$NGINX_DOMAIN`)
      traefik.http.routers.nginx.entrypoints: web

networks:
  proxy:
    external: true
