---
version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - cf-tunnel
    environment:
      - NGINX_HOST=${NGINX_HOST}
networks:
  cf-tunnel:
    external: true
