version: "3"

services:
  cloudflared:
    container_name: cloudflared

    image: cloudflare/cloudflared:latest

    restart: unless-stopped

    networks:
      - cf-tunnel

    command:
      - tunnel
      - --no-autoupdate
      - run

    env_file:
      - .env

    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  cf-tunnel:
    name: cf-tunnel
