version: "3"

services:
  cloudflared:
    container_name: cloudflared

    image: cloudflare/cloudflared:latest

    restart: unless-stopped

    networks:
      - proxy
      - monitoring

    command:
      - tunnel
      - --no-autoupdate
      - --metrics
      - cloudflared:60123
      - run

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}

networks:
  proxy:
    name: proxy
  monitoring:
    external: true
