version: "3"

services:
  cloudflared:
    container_name: cloudflared

    image: cloudflare/cloudflared:latest

    restart: unless-stopped

    networks:
      - proxy

    command:
      - tunnel
      - --no-autoupdate
      - run

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}

networks:
  proxy:
    name: proxy
