version: "3.3"
services:
  stirling-pdf:
    container_name: stirling-pdf

    image: frooodle/s-pdf:latest

    restart: unless-stopped

    networks:
      - proxy

    expose:
      - 8080

    volumes:
      - ./data/trainingData:/usr/share/tessdata
      - ./data/extraConfigs:/configs

    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB

    labels:
      traefik.enable: true
      traefik.http.routers.stirling-pdf.rule: Host(`pdf.local.$DOMAIN`) || Host(`pdf`)
      traefik.http.routers.stirling-pdf.entrypoints: websecure
      traefik.http.routers.stirling-pdf.tls: true

networks:
  proxy:
    external: true
