version: "3.3"
services:
  uptime-kuma:
    container_name: uptime-kuma

    image: "louislam/uptime-kuma:1"

    restart: always

    expose:
      - 3001

    networks:
      - proxy

    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.rule: Host(`status.local.$DOMAIN`)
      traefik.http.routers.uptime-kuma.entrypoints: websecure
      traefik.http.routers.uptime-kuma.tls: true
      traefik.http.routers.uptime-kuma.middlewares: authentik@docker
      traefik.http.routers.uptime-kuma-auth.rule: Host(`status.local.$DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.uptime-kuma-auth.entrypoints: websecure
      traefik.http.routers.uptime-kuma-auth.service: authentik

networks:
  proxy:
    external: true
